name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Start services
        run: |
          docker-compose up -d

      - name: Wait for Cassandra to be ready
        run: |
          docker-compose up -d
          docker-compose exec -T cassandra cqlsh -e "SELECT release_version FROM system.local"
          docker-compose exec -T db psql -U new_db -c "SELECT 1"

      - name: Run tests
        run: |
          pytest --cov=.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Staging
        run: |
          bash deployment/deploy_staging.sh
        if: github.ref == 'refs/heads/master'

      - name: Deploy to Production
        run: |
          bash deployment/deploy_production.sh
        if: github.ref == 'refs/tags/*'
