# Generated by Django 5.1.2 on 2024-11-18 09:57

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_userprofile_age_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='UIN',
            field=encrypted_model_fields.fields.EncryptedCharField(default='No UIN'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
    ]
