# Generated by Django 5.1.2 on 2024-11-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_datasetupload_delete_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetUpload',
        ),
    ]
