# Generated by Django 5.1.2 on 2024-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
    ]
