# Generated by Django 5.1.2 on 2024-11-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_uploadedfile_is_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_safe',
        ),
    ]
