# Generated by Django 5.1.2 on 2024-11-24 07:59

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_uploadedfile_is_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(unique=True),
        ),
    ]
