stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - name: postgres:15
    alias: db
  - name: postgres:15
    alias: replica1
  - name: postgres:15
    alias: replica2
  - name: cassandra:4.1
    alias: cassandra

before_script:
  - docker info

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker

test:
  stage: test
  script:
    - docker-compose up -d
    - docker exec app python manage.py migrate
    - docker exec app python manage.py test
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
  tags:
    - docker
