
services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:8000"
      - "8002:8000"
      - "8003:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn market.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: market.settings
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
    depends_on:
      - postgres
      - cassandra
    entrypoint: >
      /bin/sh -c "
      /wait-for-it.sh cassandra:9042 --timeout=60 --strict &&
      /wait-for-it.sh db:5432 --timeout=60 --strict &&
      gunicorn market.wsgi:application --bind 0.0.0.0:8000
      "
    networks:
      - app_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: new_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  cassandra:
    image: cassandra:4
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_LISTEN_ADDRESS: cassandra
      CASSANDRA_BROADCAST_ADDRESS: cassandra
      CASSANDRA_SEEDS: cassandra
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - app_network
    expose:
      - "7000"
      - "7001"
      - "7199"
      - "9042"
      - "9160"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pgdata:
  cassandradata:

networks:
  app_network:
    driver: bridge
