
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: myapp.settings
    depends_on:
      - db
      - cassandra
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: new_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  replica1:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: new_db
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - app_network

  replica2:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: new_db
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - app_network

  cassandra:
    image: cassandra:4.1
    environment:
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_LISTEN_ADDRESS: 0.0.0.0
      CASSANDRA_BROADCAST_ADDRESS: 127.0.0.1
      CASSANDRA_SEEDS: "127.0.0.1"
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - app_network

volumes:
  pgdata:
  pgdata1:
  pgdata2:
  cassandradata:

networks:
  app_network:
